#!/bin/bash
#
# How to run
# cd $FlyWithLua_REPO
# ./build-FlyWithLua_lin_WithDocker_win_mac_lin_WithCmake_OnLinux

rm -r FlyWithLua/64/*.xpl
rm -r src/build-lin/*

# Windows build

 rm -r build/*
 cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-x86-64.cmake
 cmake --build ./build -v
 cp ./build/win.xpl ./FlyWithLua/64/


# Linux build

# building a version for Ubuntu 18.04
# It does not have the debugging info the other build has

(cd docker; make)
cp src/build-lin/lin.xpl FlyWithLua/64/older_distro_lin.xpl

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build ./build -v
cp ./build/lin.xpl ./FlyWithLua/64/


# Mac build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-x86_64-11.3.cmake
cmake --build ./build -v
cp ./build/mac.xpl ./mac_x86_64.xpl

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-arm64-11.3.cmake -DBUILD_ARM=ON
cmake --build ./build -v
cp ./build/mac.xpl ./mac_arm64.xpl

lipo -create ./mac_x86_64.xpl ./mac_arm64.xpl -o ./FlyWithLua/64/mac.xpl
rm mac_x86_64.xpl
rm mac_arm64.xpl


cp docs/FlyWithLua_Manual_en.pdf FlyWithLua/Documentation/FlyWithLua_Manual_en.pdf

exec $SHELL
#

