#!/bin/bash
#
# How to run
# ./xp11_FlyWithLua_NG_plugin_builder/FlyWithLua/buildFlyWithLua_NG

cd ~/xp11_FlyWithLua_NG_plugin_builder/FlyWithLua

rm -r src/build-mac/*
rm -r src/build-lin/*
rm -r src/build-win/*
rm -r FlyWithLua/64/*.xpl

(cd docker; make)

cp src/build-mac/mac.xpl ~/xp11_FlyWithLua_NG_plugin_builder/FlyWithLua/FlyWithLua/64/mac.xpl

cp src/build-lin/lin.xpl ~/xp11_FlyWithLua_NG_plugin_builder/FlyWithLua/FlyWithLua/64/lin.xpl

cp src/build-win/win.xpl ~/xp11_FlyWithLua_NG_plugin_builder/FlyWithLua/FlyWithLua/64/win.xpl

exec $SHELL
#

