;FlyWithLua Preference file
; 
;All lines begining with a ; are comments
;
;William R Good
;
;DeveloperMode = 0 Disabeled  = 1 Enabeled
DeveloperMode = 0
;
;VerboseMode = 0 Disabeled  = 1 Enabeled
VerboseMode = 0

;ImguiDebugPopup = 0 Disabeled  = 1 Enabeled
ImguiDebugPopup = 0

;ImguiFontSize1 = 13 Initial font1 size
ImguiFontSize1 = 13

;ImguiFontSize2 = 16 Initial font2 size
ImguiFontSize2 = 16

;ImguiFontSize3 = 20 Initial font3 size
ImguiFontSize3 = 20
